apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: your-registry/celery_workers:latest
        env:
        - name: BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
        - name: BACKEND_URL
          value: "redis://redis:6379/0"
