apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service-consumer
  labels:
    app: credit-service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-service-consumer
  template:
    metadata:
      labels:
        app: credit-service-consumer
    spec:
      containers:
      - name: credit-service-consumer
        image: your-registry/credit_service:latest
        command: ["python", "consumer.py"]
        env:
          - name: DATABASE_URL
            value: "postgresql://user:password@postgresql-credit:5432/credit_db"
          - name: BROKER_URL
            value: "amqp://guest:guest@rabbitmq:5672//"
