apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  # These are base64 encoded values
  POSTGRES_USER: bG9hbl91c2Vy  # loan_user
  POSTGRES_PASSWORD: bG9hbl9wYXNzd29yZA==  # loan_password
  POSTGRES_DB: bG9hbl9kYg==  # loan_db 