apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-service-api
  labels:
    app: decision-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision-service-api
  template:
    metadata:
      labels:
        app: decision-service-api
    spec:
  containers:
    - name: decision-service-api
      image: your-registry/decision_service:latest
      ports:
        - containerPort: 8000
      env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgresql-service:5432/decision_db"
        - name: BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"

