apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-service-consumer
  labels:
    app: decision-service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decision-service-consumer
  template:
    metadata:
      labels:
        app: decision-service-consumer
    spec:
      containers:
      - name: decision-service-consumer
        image: your-registry/decision_service:latest
        command: ["python", "consumer.py"]
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgresql-service:5432/decision_db"
        - name: BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
