apiVersion: v1
kind: Service
metadata:
  name: notification-service-api
spec:
  selector:
    app: notification-service-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
