apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-script
data:
  init.sql: |
    -- Create schemas
    CREATE SCHEMA IF NOT EXISTS loan;
    CREATE SCHEMA IF NOT EXISTS credit;
    CREATE SCHEMA IF NOT EXISTS property;
    CREATE SCHEMA IF NOT EXISTS notification;
    CREATE SCHEMA IF NOT EXISTS decision;

    -- Grant privileges to loan_user
    GRANT USAGE ON SCHEMA loan TO loan_user;
    GRANT USAGE ON SCHEMA credit TO loan_user;
    GRANT USAGE ON SCHEMA property TO loan_user;
    GRANT USAGE ON SCHEMA notification TO loan_user;
    GRANT USAGE ON SCHEMA decision TO loan_user;

    -- Grant table creation privileges
    ALTER DEFAULT PRIVILEGES IN SCHEMA loan GRANT ALL ON TABLES TO loan_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA credit GRANT ALL ON TABLES TO loan_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA property GRANT ALL ON TABLES TO loan_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON TABLES TO loan_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA decision GRANT ALL ON TABLES TO loan_user; 