apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service-api
  labels:
    app: property-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service-api
  template:
    metadata:
      labels:
        app: property-service-api
    spec:
      containers:
      - name: property-service-api
        image: your-registry/property_service:latest
        ports:
        - containerPort: 8000
        env:
        - name: BROKER_URL
          value: "amqp://guest:guest@rabbitmq:5672//"
